Warning in .ddg.insert.error.message(error.msg) :[1] "Error in file(con, \"w\"): cannot open the connection\n"

  Unable to evaluate ww in call to ddg.data
Warning in .ddg.insert.error.message(error.msg) :
  Unable to evaluate xx in call to ddg.data
Warning in .ddg.insert.error.message(error.msg) :
  Skipping parameter vector
Warning in .ddg.insert.error.message(error.msg) : Skipping parameter 
Warning in .ddg.insert.error.message(error.msg) :
  No data node found for a b c
Warning in .ddg.insert.error.message(error.msg) :
  No data node found for no.such.data.node
Warning in file(con, "w") :
  cannot open file '/Users/blerner/tmp/testfile2.txt': No such file or directory
